### ISSUE TITLE
Package doesn't seem to be working

### ISSUE THREAD

**Issue by anmolonruby** [zurb/foundation-5-sublime-snippets#27]
I installed exactly the way it's mentioned in instructions. It's in my package folder and I could see all the snippets, but I am unable to use them in Sublime text. When I type the shortcuts, nothing happens. No suggestion box, no full expansion when I hit tab.

I have sublime text 3 working on Max OS X Mavericks.

**Comment by lbezerra** [comment]
same here

**Comment by joelkinzel** [comment]
I wish this would work without the filename having to be set. Minor thing, but...

**Comment by jamesstoneco** [comment]
can't you just change the syntax to html?
